# Generated by Django 3.2.25 on 2025-02-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('description_short', models.TextField(verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Длинное название')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('lan', models.FloatField(verbose_name='Широта')),
            ],
        ),
    ]
