# Generated by Django 3.2.25 on 2025-02-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20250214_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lan',
            new_name='lat',
        ),
    ]
