# Generated by Django 4.2.20 on 2025-04-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_remove_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
